#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <unistd.h> /* for write() */
#include <wchar.h>

wint_t fputwc(wchar_t c, FILE *f) {
    if(!f)
        return WEOF;

    int mode = fwide(f, 0);
    if(mode < 0)
        return WEOF;
    else if(mode == 0)
        fwide(f, 1);

    _spin_lock(&f->_lock);

    char buf[MB_LEN_MAX];
    size_t len = wcrtomb(buf, c, &f->_mbstate);

    if(len == (size_t)-1) {
        f->_flags |= __S_ERR;
        errno = EILSEQ;
        _spin_unlock(&f->_lock);
        return WEOF;
    }

    /* Ensure stream is in write mode ONCE for the whole sequence */
    if(f->_flags & __S_RD) {
        f->_flags &= ~__S_RD;
        f->_flags |= __S_WR;
        f->_cnt = f->_bsize;
        f->_ptr = f->_base;
    } else if(!(f->_flags & __S_WR)) {
        f->_flags |= __S_WR;
        if(f->_cnt == 0 && f->_ptr == f->_base) {
            f->_cnt = f->_bsize;
        }
    }

    /* Unbuffered stream: write the entire multibyte sequence in one syscall!
     * This is a massive optimization over byte-by-byte unbuffered writes. */
    if(f->_flags & __S_NBF) {
        if(write(f->_fd, buf, len) != (ssize_t)len) {
            f->_flags |= __S_ERR;
            _spin_unlock(&f->_lock);
            return WEOF;
        }
        _spin_unlock(&f->_lock);
        return (wint_t)c;
    }

    /* Logic for buffered streams (_IOFBF, _IOLBF) 
     * We loop over the generated bytes and push them into the buffer */
    for(size_t i = 0; i < len; i++) {
        if(f->_cnt == 0) {
            if(__stdio_flush_impl(f) != 0) {
                _spin_unlock(&f->_lock);
                return WEOF;
            }
        }

        *f->_ptr++ = (unsigned char)buf[i];
        f->_cnt--;
        f->_flags |= __S_DIRTY;

        /* Flush if buffer is full, or line-buffered and we hit a newline */
        if(f->_cnt == 0 || ((f->_flags & __S_LBF) && buf[i] == '\n')) {
            if(__stdio_flush_impl(f) != 0) {
                _spin_unlock(&f->_lock);
                return WEOF;
            }
        }
    }

    _spin_unlock(&f->_lock);
    return (wint_t)c;
}
